const CACHE_NAME='gd-web-core-v11-sw-20260915';
const SHELL=['./','./index.html','./ref/favicon.png','./gd_web.js','./chunks/manifest.json'];
const PROXY_URL='https://geometrydash.thisisacallfor.help/_proxy';
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(SHELL)).catch(()=>null).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('gd-web-')&&key!==CACHE_NAME).map(key=>caches.delete(key)))),self.clients.claim()]))});
async function getCachedOrNetwork(request){let response=await caches.match(request,{ignoreSearch:false});if(response)return response;response=await fetch(request);if(response&&response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy)).catch(()=>{})}return response}
function isProxyRequest(url){return url.origin===self.location.origin&&/(?:^|\/)(?:proxy|__proxy|_proxy)\/?$/.test(url.pathname)}
async function forwardProxy(request,url){const target=new URL(PROXY_URL);for(const [key,value] of url.searchParams)target.searchParams.append(key,value);const headers=new Headers;for(const name of ['accept','content-type','range']){const value=request.headers.get(name);if(value)headers.set(name,value)}const init={method:request.method,headers,mode:'cors',credentials:'omit',redirect:'follow',cache:'no-store'};if(request.method!=='GET'&&request.method!=='HEAD')init.body=await request.clone().arrayBuffer();return fetch(target.toString(),init)}
self.addEventListener('fetch',event=>{const request=event.request;const url=new URL(request.url);if(isProxyRequest(url)){event.respondWith(forwardProxy(request,url));return}if(request.method!=='GET'||url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(fetch(request).catch(()=>caches.match('./index.html')));return}const cacheable=url.pathname.endsWith('/gd_web.js')||url.pathname.includes('/chunks/')||url.pathname.includes('/ref/');if(cacheable)event.respondWith(getCachedOrNetwork(request))});
